config/routes.rb
Rails.application.routes.draw do
  resources :postings
  devise_for :users
  #adding home page
  root 'pages#landing'

  #adding mission page
  get 'mission' => 'pages#mission'

  #adding signup page
  get 'signup' => 'pages#signup'

  #adding login page
  get 'login' => 'pages#login'

end

app/models/posting.rb
class Posting < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :postings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def postings
  end

  def mission
  end

  def login
  end

  def signup
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @postings = Posting.all
  end

  def show
  end

  def new
    @posting = current_user.postings.build
  end

  def edit
  end

  def create
    @posting = current_user.postings.build(posting_params)
    if @posting.save
      redirect_to @posting, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @posting.update(posting_params)
      redirect_to @posting, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @posting.destroy
    redirect_to postings_url
  end

  private
    def set_posting
      @posting = Posting.find_by(id: params[:id])
    end

    def correct_user
      @posting = current_user.postings.find_by(id: params[:id])
      redirect_to postings_path, notice: "Not authorized to edit this post" if @posting.nil?
    end

    def posting_params
      params.require(:posting).permit(:image, :title, :description, :category, :condition, :price, :offer_shipping, :shipping_size, :offer_local_pickup)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img alt="Brand" src="/images/yerdleicon.png"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Mission", mission_path %></li>
        <li><%= link_to "Get the App", "#" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><a href="#">$25</a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZerdleRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>

    <%= yield %>

  <h3>Discover</h3>
    <p>Get the App</p>
    <p>Invite Friends</p>
    <p>Support</p>
    <p>Unshopping Challenge</p>
    <p>Login</p>

  <h3>About Us</h3>
    <p>Mission</p>
    <p>Press</p>
    <p>Jobs</p>

  <h3>Connect</h3>
    <p>Facebook</p>
    <p>Twitter</p>
    <p>Instagram</p>
    <p>Blog</p>
  <h6>© 2015 Zerdle · 007 Bond Street, San Francisco, CA · Privacy & Terms</h6>
</body>
</html>

app/views/pages/home.html.erb
Welcome to Zerdle

<p>See what other people are giving right now.</p>

app/views/pages/landing.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-4 center">
    <h1>More Joy, Less Stuff</h1>
    <p>Post a pic of your unused stuff & shop for what you need.</p>

    <p>Available for iOS and Android</p>
    <p><%= link_to "Get the App", "#", class:"btn btn-default" %></p>
  </div>
</div>

<p>"Discard everything that does not give you joy."</p>
<h6>MARIE KONDO</h6>

<h3>How It Works</h3>

<h3>Post a pic</h3>
  <p>Post a pic of stuff you once loved but don't need anymore. Check your closet, garage, or kitchen - you'll find plenty of sthings that someone else could use.</p>

<h3>Let it go</h3>
  <p>Ship your item to its new home. We provide pre-paid UPS shipping labels to make it easy. Anything under 10lbs can be shipped on Yerdle.</p>

<h3>Get what you need</h3>
  <p>By giving your stuff on Yerdle, you earn Yerdle Reuse Dollars. Use your Yerdle Dollars to get anything you want in the Yerdle store, without spending cash.</p>

<div class="center landing_color">
  <h3>RECENTLY FEATURED IN</h3>
    <p>Fast Company * USA Today * Time * Business Insider * The New York Times * SFGate</p>
</div>
<div class="center">
  <h2>Available Now</h2>
    <p>For iOS and Android. Get the app.</p>
    <p>Downoad on the App Store * Get it on Google play</p>
</div>

app/views/pages/mission.html.erb
<div class="container">
  <h1>Mission</h1>
  <p>Our mission is to reduce the number of new things we all have to buy by 25%.

  Our relationship with stuff is broken. We all feel overwhelmed by our clutter, even as we race along the treadmill of buying more stuff.

  We need to make a change.

  At Yerdle, we want to redefine the word “mine.” We want to let go of our attachment to things we almost never use. We want to change the way we think about our belongings in the context of a finite planet, busy lives, and better uses for our hard-earned dollars.

  Yerdle’s mission is to reduce the number of new things we all need to buy by 25%.

  We formed ourselves as a California Benefit Corporation, so that our mission is written into our legal charter and nothing can stop us on our path towards completing our mission.

  Almost everyone has stuff they’re not using that's ready for its next adventure. We make it easy to give your item to someone who needs it.

  People give tens of thousands of items on Yerdle each month. Over 200,000 items so far.

  Join us.</p>
</div>

app/views/pages/postings.html.erb
<div class="container">

  <h1>See what other people are giving right now.</h1>

  <a href="#">Now Trending</a>
  <a href="#">Categories</a>
</div>

app/views/postings/_form.html.erb
<%= form_for @posting, html: {multipart: true} do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% @posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :offer_shipping %><br>
    <%= f.check_box :offer_shipping %>
  </div>
  <div class="field">
    <%= f.label :shipping_size %><br>
    <%= f.text_field :shipping_size %>
  </div>
  <div class="field">
    <%= f.label :offer_local_pickup %><br>
    <%= f.check_box :offer_local_pickup %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postings/edit.html.erb
<h1>Editing Posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Now Trending</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>Giver</th>
      <th>Category</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Offer shipping</th>
      <th>Shipping size</th>
      <th>Offer local pickup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= image_tag posting.image.url(:medium) %></td>
        <td><%= posting.title %></td>
        <td><%= posting.description %></td>
        <td><%= posting.user.first_name %> <%= posting.user.last_name %></td>
        <td><%= posting.category %></td>
        <td><%= posting.condition %></td>
        <td><%= posting.price %></td>
        <td><%= posting.offer_shipping %></td>
        <td><%= posting.shipping_size %></td>
        <td><%= posting.offer_local_pickup %></td>
        <td><%= link_to 'Show', posting %></td>
        <% if posting.user == current_user %>
          <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
          <td><%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Posting', new_posting_path %>
<% end %>

app/views/postings/new.html.erb
<h1>New Posting</h1>

<%= render 'form' %>

<%= link_to 'Back', postings_path %>

app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @posting.image.url(:medium) %>
</p>

<p>
  <strong>Title:</strong>
  <%= @posting.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @posting.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @posting.category %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @posting.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @posting.price %>
</p>

<p>
  <strong>Offer shipping:</strong>
  <%= @posting.offer_shipping %>
</p>

<p>
  <strong>Shipping size:</strong>
  <%= @posting.shipping_size %>
</p>

<p>
  <strong>Offer local pickup:</strong>
  <%= @posting.offer_local_pickup %>
</p>

<% if @posting.user == current_user %>
  <%= link_to 'Edit', edit_posting_path(@posting) %> |
<% end %>
<%= link_to 'Back', postings_path %>